language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-plpython-10
install:
  - sh install_dependencies.sh
  - sudo make install
script:
  - python3 -m pytest 
  # FIXME: 
  # The line below tests the postgres functions,
  # but I can't get plpython3u working in travis,
  # so the tests are failing.
  #- make installcheck || { cat regression.diffs; false; }
